### PR TITLE
fatal error: concurrent map read and map write

### PR DESCRIPTION
**Pull request by ddkwork**

### CODE REVIEW

**Review by kkoreilly — CHANGES_REQUESTED** [review]
If you are only using the `RWMutex` for write-locking, shouldn't it just be a `Mutex`? Also, can you make the mutex a field called `mu` instead of embedding it? Thanks!

**Comment by ddkwork** [comment]
> If you are only using the `RWMutex` for write-locking, shouldn't it just be a `Mutex`? Also, can you make the mutex a field called `mu` instead of embedding it? Thanks!

okay

**Review by kkoreilly — APPROVED** [review]
Thanks!

**Comment by kkoreilly** [comment]
Active in `v1.0.4`. Also, in the future, please always run `go mod tidy` in your PRs.

**Comment by ddkwork** [comment]
> Active in `v1.0.4`. Also, in the future, please always run `go mod tidy` in your PRs.

okay

**Pull request merged**
